from general import item

itemlist = []

itemlist.append(item("IceBreath", "Ice Fairy Scroll", "ability"))
itemlist.append(item("QuickEscape", "Fairy Spell Book", "ability"))
itemlist.append(item("Lamp", "Yeti Lamp", "ability"))
itemlist.append(item("Mint", "Super Breath Mint", "ability"))
itemlist.append(item("Top", "Magic Spinning Top", "ability"))
itemlist.append(item("Pepper", "Hot Banana Pepper", "ability"))
itemlist.append(item("Statue", "Kangaroo Carving", "ability"))
itemlist.append(item("Dynamo", "Mini Dynamo", "ability"))
itemlist.append(item("HealthBar", "Super Health Bar", "ability"))
itemlist.append(item("Glasses", "Phoenix Shades", "ability"))
itemlist.append(item("Antennae", "Antennae Extensions", "ability"))
itemlist.append(item("Warp", "Spot-On Warp Device", "ability"))

itemlist.append(item("RainbowDust", "Magic Rainbow Dust", "bonus"))
itemlist.append(item("RedDust", "Magic Red Dust", "bonus"))
itemlist.append(item("GreenDust", "Magic Green Dust", "bonus"))
itemlist.append(item("BlueDust", "Magic Blue Dust", "bonus"))
itemlist.append(item("GoldDust", "Magic Gold Dust", "bonus"))

itemlist.append(item("RedKey1", "Left Half of the Red Chest Key", "keyhalf"))
itemlist.append(item("RedKey2", "Right Half of the Red Chest Key", "keyhalf"))
itemlist.append(item("GreenKey1", "Left Half of the Green Chest Key", "keyhalf"))
itemlist.append(item("GreenKey2", "Right Half of the Green Chest Key", "keyhalf"))
itemlist.append(item("PurpleKey1", "Left Half of the Purple Chest Key", "keyhalf"))
itemlist.append(item("PurpleKey2", "Right Half of the Purple Chest Key", "keyhalf"))
itemlist.append(item("YellowKey1", "Left Half of the Yellow Chest Key", "keyhalf"))
itemlist.append(item("YellowKey2", "Right Half of the Yellow Chest Key", "keyhalf"))

itemlist.append(item("DSHeart", "Heart of the Dragon Shores", "heart"))
itemlist.append(item("FLHeart", "Heart of the Fairy Library", "heart"))
itemlist.append(item("YSHeart", "Heart of the Yeti Serengeti", "heart"))
itemlist.append(item("BBHeart", "Heart of Byrd Barracks", "heart"))
itemlist.append(item("TGHeart", "Heart of the Thieves' Guild", "heart"))
itemlist.append(item("RHHeart", "Heart of the Rabbit Habitat", "heart"))
itemlist.append(item("BSHeart", "Heart of the Banana Savannah", "heart"))
itemlist.append(item("KHHeart", "Heart of the Kangaroo Hoodoos", "heart"))
itemlist.append(item("MMHeart", "Heart of Moneybags' Mansion", "heart"))
itemlist.append(item("CSHeart", "Heart of the Cheetah Spot Spa", "heart"))
itemlist.append(item("RCHeart", "Heart of Rhynocs n' Clocks", "heart"))
itemlist.append(item("CRHeart", "Heart of Chateau Ripto", "heart"))

itemlist.append(item("SpyroDoll", "Spyro Action Figure", "quest"))
itemlist.append(item("RiptoDoll", "Ripto Action Figure", "quest"))
itemlist.append(item("BiancaDoll", "Bianca Action Figure", "quest"))
itemlist.append(item("HunterDoll", "Hunter Action Figure", "quest"))
itemlist.append(item("SheilaDoll", "Sheila Action Figure", "quest"))
itemlist.append(item("ByrdDoll", "Sgt. Byrd Action Figure", "quest"))
itemlist.append(item("AgentDoll", "Agent 9 Action Figure", "quest"))
itemlist.append(item("Extenso", "Extenso-Grip Attachment", "quest"))
itemlist.append(item("BookBGone", "Book-B-Gone Storage Unit", "quest"))
itemlist.append(item("DustingArm", "No-Sneeze Dusting Armature", "quest"))
itemlist.append(item("EyeSpy", "Eye-Spy Binding Scanner", "quest"))
itemlist.append(item("Motivator", "Quick-N-Quiet Motivator Unit", "quest"))
itemlist.append(item("SortingMod", "Sup-R-Smart Sorting Module", "quest"))
itemlist.append(item("UserManual", "Dusty User Manual", "quest"))
itemlist.append(item("YetiRope", "Yeti Hair Climbing Rope", "quest"))
itemlist.append(item("LuckyHat", "Lucky Climbing Hat", "quest"))
itemlist.append(item("LeftShoe", "Big Left Climbing Shoe", "quest"))
itemlist.append(item("LeftShoe2", "Another Left Climbing Shoe", "quest"))
itemlist.append(item("LeftGlove", "Huge Left Climbing Glove", "quest"))
itemlist.append(item("RightGlove", "Huge Right Climbing Glove", "quest"))
itemlist.append(item("MountainAxe", "Enormous Mountaineer's Axe", "quest"))
itemlist.append(item("Liberation", "Medal of Liberation", "quest"))
itemlist.append(item("ArcticCross", "The Arctic Cross", "quest"))
itemlist.append(item("HerosMedal", "Hero's Heart Medal", "quest"))
itemlist.append(item("MedalHonor", "Medal of Honor", "quest"))
itemlist.append(item("VictoryMedal", "Victory Medal", "quest"))
itemlist.append(item("MilitaryCross", "Military Cross", "quest"))
itemlist.append(item("OrderMerit", "The Order of Merit", "quest"))
itemlist.append(item("Stethoscope", "Master's Stethoscope", "quest"))
itemlist.append(item("NailFile", "Master's Nail File", "quest"))
itemlist.append(item("HandDrill", "Master's Hand Drill", "quest"))
itemlist.append(item("Crowbar", "Master's Crowbar", "quest"))
itemlist.append(item("Sledgehammer", "Master's Sledgehammer", "quest"))
itemlist.append(item("Fuse", "Master's Fuse", "quest"))
itemlist.append(item("Explosives", "Master's Explosives", "quest"))
itemlist.append(item("DragonStar", "Dragon Star", "quest"))
itemlist.append(item("YetiLettuce", "Yeti Lettuce", "quest"))
itemlist.append(item("SnowLily", "Snow Lily", "quest"))
itemlist.append(item("ApeGrapes", "Ape Grapes", "quest"))
itemlist.append(item("RoosRose", "Roo's Rose", "quest"))
itemlist.append(item("MoneyTree", "Money Tree", "quest"))
itemlist.append(item("SunspotBloom", "Sunspot Bloom", "quest"))
itemlist.append(item("RipeAgent", "Banana Ripening Agent", "quest"))
itemlist.append(item("BananaDust", "Magic Banana Dust", "quest"))
itemlist.append(item("FlavorBoost", "Flavor Booster", "quest"))
itemlist.append(item("SoilStable", "Soil Stabilizer", "quest"))
itemlist.append(item("PeelStrength", "Peel Strengthener", "quest"))
itemlist.append(item("GroGrowth", "Banana Gro-Growth", "quest"))
itemlist.append(item("YellowDye", "Yellow Dye #5", "quest"))
itemlist.append(item("RooZetta", "The Zoo Retta Stone", "quest"))
itemlist.append(item("KangaHistory", "Kangaroo History", "quest"))
itemlist.append(item("RooJewel", "The Roo Jewel", "quest"))
itemlist.append(item("Doodle", "Digeri-doodle", "quest"))
itemlist.append(item("Brochure", "Ancient Travel Brochure", "quest"))
itemlist.append(item("Boomerang", "Ceremonial Boomerang", "quest"))
itemlist.append(item("Pottery", "Roo Pottery", "quest"))
itemlist.append(item("Organ", "Hypnotic Light Organ", "quest"))
itemlist.append(item("Uniform", "Totally Retro Uniform", "quest"))
itemlist.append(item("Trophy", "Hip Neon Trophy", "quest"))
itemlist.append(item("LavaLamp", "Way Cool Lava Lamp", "quest"))
itemlist.append(item("Painting", "Groovy Painting", "quest"))
itemlist.append(item("Snowboard", "Wild Snowboard", "quest"))
itemlist.append(item("Wing", "Awesome Dragonfly Wing", "quest"))
